version: '3'
services:
  connector-template:
    image: opencti/connector-template:5.3.7
    environment:
      - OPENCTI_URL=http://10.0.0.138:8080
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=BulkCsv
      - CONNECTOR_SCOPE=text/csv # MIME type or Stix Object
      - CONNECTOR_CONFIDENCE_LEVEL=100 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
