opencti:
  url: 'http://10.0.0.138:8080/opencti'
  token: '1d2f63af-6fcc-4757-95fa-9c525a5375d2'

connector:
  id: '3b0f4caa-42e3-49b9-81ec-d8e564731348'
  type: 'INTERNAL_ENRICHMENT'
  name: 'ReportEnrich'
  scope: 'REPORT' # MIME type or SCO
  confidence_level: 100 # From 0 (Unknown) to 100 (Fully trusted)
  log_level: 'info'
