opencti:
  url: 'http://10.0.0.138:8080'
  token: '1d2f63af-6fcc-4757-95fa-9c525a5375d2'

connector:
  id: 'f42a38a0-4e9f-4165-a727-a680bbfbeafb'
  type: 'EXTERNAL_IMPORT'
  name: 'MISP Patched' # Required
  scope: 'misp'
  confidence_level: 25 # 0 (Unknown) or from 1 to 100
  update_existing_data: False
  log_level: 'info'

misp:
  url: 'https://10.0.0.138' # Required
  reference_url: '' # Optional, will be used to create external reference to MISP event
  key: '8fJDJ78NS4gjwINUpE07KaqHA42Wo0p332vtkvUC' # Required
  ssl_verify: False # Required
  datetime_attribute: 'timestamp' # Required, filter to be used in query for new MISP events
  create_reports: True # Required, create report for MISP event
  create_indicators: True # Required, create indicators for attributes
  create_observables: True # Required, create observables for attributes
  create_object_observables: True # Required, create text observables for MISP objects
  report_type: 'misp-event' # Optional, report_class if creating report for event
  report_status: 'New' # New, In progress, Analyzed and Closed
  import_from_date: '2010-01-01' # Optional, import all event from this date
  import_creator_orgs_not: '' # Optional, do not import events created by those orgs (put the identifiers here)
  import_owner_orgs_not: '' # Optional, do not import events owned by those orgs (put the identifiers here)
  import_owner_keyword: '' # Optional, search only events based on a keyword
  import_with_attachments: True # Optional, try to import a PDF file from the attachment attribute
  import_unsupported_observables_as_text: False # Optional, import unsupported observable as x_opencti_text
  interval: 1 # Required, in minutes
